### ISSUE TITLE
hints to dig in the code

### ISSUE THREAD

**Issue by smichea** [utext/utext.github.io#1]
Hi @gochev ,

I found your  mockup in markdown project very interesting and wanted to check the code to see if we can participate.
It seems the code on this repo is produced from some source code that is not available. Do you plan to release it ?

Congrats for your work,
Best regards

**Comment by gochev** [comment]
Oh yes super sorry I will release it next week it is not on GitHub but one super old internal git I will move it to here

**Comment by gochev** [comment]
@smichea  it is over here https://github.com/gochev/utext
